name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v2.5.0
          args: release --clean --snapshot --skip=publish